---
# List of custom programs to install that are not packaged. These each require 
# a install_name function in the appropriate place in the 'custom' directory to
# define the steps for downloading, building, and installing the package.
bio_general:
bio_nextgen:
  alignment:
  utilitites:
  analysis:
  assembly:
  chip:
  needs_64bit:
distributed:
python:
java:
